ResturanShemronKabab/Controllers/AppetizerManagementController.cs
using FrameWork;
using FrameWork.DTOS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Restaurant.Application;
using Restaurant.ApplicationServiceContract.Services;
using Restaurant.DomainModel.ApplicationModel.Appetizer;
using Restaurant.DomainModel.ApplicationModel.Category;
using Restaurant.DomainModel.ApplicationModel.Food;
using ResturanShemronKabab.ViewModel;
using System.Security.Policy;

namespace ResturanShemronKabab.Controllers
{
	public class AppetizerManagementController : Controller
	{
		private readonly IAppetizerApplication appetizerApplication;

		private readonly ICategoryApplication categoryApplication;

        private readonly IHostEnvironment env;

        public AppetizerManagementController(IAppetizerApplication appetizerApplication , ICategoryApplication categoryApplication, IHostEnvironment env) 
        {
            this.appetizerApplication = appetizerApplication;
			this.categoryApplication = categoryApplication;
			this.env = env;
        }

        public IActionResult Index(AppetizerSearchModel sm)
		{
			InflateCategoryDrp();
			return View(sm);
		}

		public IActionResult List()
		{
			var Aappe = appetizerApplication.GetAllListItem();
			return View(Aappe);
		}

		public IActionResult ListUI()
		{
			var appetizer = appetizerApplication.GetAllListItemInUI();
			return View(appetizer);
		}

		private void InflateCategoryDrp()
		{
			var Cat = categoryApplication.GetDrp();
			Cat.Insert(0, new CategoryListForDrp { CategoryID = -1, CategoryName = "...Please Select..." });
			SelectList categoryDropDown = new SelectList(Cat, "CategoryID", "CategoryName");
			ViewBag.categoryDropDown = categoryDropDown;
		}

		public IActionResult Add(int id)
		{
			InflateCategoryDrp();
			return View();
		}
        [HttpPost]
        public IActionResult Add(AppetizerAddEditViewModel model)
        {
            if (model.Picture == null)
            {
                InflateCategoryDrp();
                TempData["ErrorMessage"] = "Please select the food";
                return View(model);
            }
            string PhisycalAddress = Path.GetFileName(model.Picture.FileName);
            string Relativeaddress = @"~/Images/" + PhisycalAddress;
            PhisycalAddress = env.ContentRootPath + @"\wwwroot\Images\" + PhisycalAddress;
            FileStream fs = new FileStream(PhisycalAddress, FileMode.Create);
            {
                model.Picture.CopyTo(fs);
            };
            AppetizerAddAndEditModel appetizerAddAndEditModel = new AppetizerAddAndEditModel
            {
                ImageURL = Relativeaddress,
				AppetizerID = model.AppetizerID,
				CategoryID = model.CategoryID,
				AppetizerName = model.AppetizerName,
			    SmallDescription = model.SmallDescription,
				UnitPrice = model.UnitPrice,
               
            };
            var op = appetizerApplication.Register(appetizerAddAndEditModel);
            if (!op.Success)
            {
                InflateCategoryDrp();
                TempData["ErrorMessage"] = op.Message;
                return View(model);
            }
            return RedirectToAction("index");
        }

        [HttpPost]
		public JsonResult Remove(int id)
		{
			//var appetizer = appetizerApplication.Get(id);
			//if (!string.IsNullOrEmpty(appetizer.ImageURL))
			//{
			//	var url = env.ContentRootPath + @"\wwwroot" + appetizer.ImageURL.Substring(1, appetizer.ImageURL.Length - 1).Replace(@"/", @"\");
			//	if (System.IO.File.Exists(url))
			//	{
			//		System.IO.File.Delete(url);
			//	}
			//}
			var op = appetizerApplication.Remove(id);
			return Json(op);
		}

		public IActionResult Search(AppetizerSearchModel searchModel)
		{
			var appetizer = appetizerApplication.Search(searchModel, out int recordCount);
			return PartialView("List", appetizer);
		}

		public IActionResult Update(int appetizerID)
		{
			var oldAppetizer = appetizerApplication.Get(appetizerID);
			InflateCategoryDrp();
			var appetizer = new AppetizerDetailsModel
			{
				AppetizerID = appetizerID,
				AppetizerName = oldAppetizer.AppetizerName,
				CategoryID = oldAppetizer.CategoryID,
				ImageURl = oldAppetizer.ImageURL,
				UnitPrice = oldAppetizer.UnitPrice,
				SmallDescription = oldAppetizer.SmallDescription,
			};
			return View(appetizer);
		}

		[HttpPost]
		public IActionResult Update(AppetizerAddEditViewModel model)
		{
			var oldAppetizer = appetizerApplication.Get(model.AppetizerID);
			if (model.Picture == null)
			{
				AppetizerAddAndEditModel NewAppetizer = new AppetizerAddAndEditModel
				{
					ImageURL = oldAppetizer.ImageURL,
					AppetizerID = model.AppetizerID,
					AppetizerName = model.AppetizerName,
					UnitPrice = model.UnitPrice,
					SmallDescription = model.SmallDescription,
					CategoryID =model.CategoryID,
				};
				var opExist = appetizerApplication.Update(NewAppetizer);
				var appetizer = new AppetizerDetailsModel
				{
					AppetizerID = oldAppetizer.AppetizerID,
					AppetizerName = oldAppetizer.AppetizerName,
					UnitPrice = oldAppetizer.UnitPrice,
					SmallDescription = oldAppetizer.SmallDescription,
					CategoryID = oldAppetizer.CategoryID,
					ImageURl = oldAppetizer.ImageURL,
				};
				if (!opExist.Success)
				{
					InflateCategoryDrp();
					TempData["ErrorMessage"] = opExist.Message;
					return View(appetizer);
				}
				return RedirectToAction("Index");
			}

			else//agar ax bood
			{

				if (!string.IsNullOrEmpty(oldAppetizer.ImageURL) && oldAppetizer.ImageURL.ToLower() != "~/images/noimage.png")
				{
					var url = env.ContentRootPath + @"\wwwroot" + oldAppetizer.ImageURL.Substring(1, oldAppetizer.ImageURL.Length - 1).Replace(@"/", @"\");
					if (System.IO.File.Exists(url))
					{
						System.IO.File.Delete(url);
					}
				}
				string PhisycalAddress = Path.GetFileName(model.Picture.FileName);
				string Relativeaddress = @"~/Images/" + PhisycalAddress;
				PhisycalAddress = env.ContentRootPath + @"\wwwroot\Images\" + PhisycalAddress;
				using (FileStream fs = new FileStream(PhisycalAddress, FileMode.Create))
				{
					model.Picture.CopyTo(fs);
				}
				AppetizerAddAndEditModel n = new AppetizerAddAndEditModel
				{
					AppetizerName = model.AppetizerName,
					ImageURL = Relativeaddress,
					AppetizerID = model.AppetizerID,
					SmallDescription = model.SmallDescription,
					CategoryID = model.CategoryID,
					UnitPrice = model.UnitPrice,
				};
				var op = appetizerApplication.Update(n);
				var appetizer = new AppetizerDetailsModel
				{
					AppetizerID = oldAppetizer.AppetizerID,
					CategoryID = oldAppetizer.CategoryID,
					ImageURl = oldAppetizer.ImageURL,
					SmallDescription = oldAppetizer.SmallDescription,
					UnitPrice = oldAppetizer.UnitPrice,
					AppetizerName = oldAppetizer.AppetizerName,
				};
				if (op.Success)
				{
					return RedirectToAction("index");

				}
				else
				{
					InflateCategoryDrp();
					TempData["ErrorMessage"] = op.Message;
					return View(appetizer);
				}

			}
		}

		[HttpPost]
		public JsonResult DeleteImage(int appetizerID)
		{
			var n = appetizerApplication.Get(appetizerID);
			if (n != null && !string.IsNullOrEmpty(n.ImageURL) && n.ImageURL.ToLower() != @"~/images/noimage.png")
			{
				var url = Path.Combine(env.ContentRootPath, "wwwroot", n.ImageURL.Substring(1).Replace("/", "\\"));
				if (System.IO.File.Exists(url))
				{
					System.IO.File.Delete(url);
				}
			}
			OperationResult op = new OperationResult("Delete Image ");
			try
			{
				appetizerApplication.RemoveImage(appetizerID);
				return Json(op.ToSuccess("Delete Image Success Fully"));
			}
			catch (Exception ex)
			{
				return Json(op.ToFail("Image did not Removed"));
			}
		}
	}
}

ResturanShemronKabab/Views/AppetizerManagement/Add.cshtml
 
@model ResturanShemronKabab.ViewModel.AppetizerAddEditViewModel
@{
	Layout = null;
    SelectList categoryDropDown = (SelectList)ViewBag.categoryDropDown;
}
<h4>Add New Appetizer</h4>
<hr />
@*
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" asp-controller="AppetizerManagement" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="CategoryID">Category</label>
                <select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
            </div>
            <div class="form-group">
                <label asp-for="AppetizerName" class="control-label"></label>
                <input asp-for="AppetizerName" class="form-control" type="text" placeholder="Appetizer Name" id="Name" data-Err-Name="spnErrName" data-msg="Enter your Appetizer Name correctly" oninput="ValidationName(this)" />
                <span class="text-danger" id="spnErrName"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" type="text" placeholder="UnitPrice" id="UnitPrice" data-Err-UnitPrice="spnErrUnitPrice" data-msg="Enter your UnitPrice correctly" oninput="ValidationUnitPrice(this)" />
                <span class="text-danger" id="spnErrUnitPrice"></span>
            </div>
            <div class="form-group">
                <label asp-for="SmallDescription" class="control-label"></label>
                <input asp-for="SmallDescription" class="form-control" type="text" placeholder="Small Description" id="SmallDescription" data-Err-SmallDescription="spnErrSmallDescription" data-msg="Enter your Small Description correctly" oninput="ValidationSmallDescription(this)" />
                <span class="text-danger" id="spnErrSmallDescription"></span>
            </div>
            <div class="form-group">
                <span>Picture</span>
                <input type="file" name="Picture" id="Picture" value="" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
 *@

<h4 style="display: flex; justify-content: center; margin-right: 60px;">
    Update Food
</h4>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <link href="~/content/font-awesome.css" rel="stylesheet" />
    <link href="~/content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/stylesheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ResturanShemronKabab.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="~/css/sweetalert2.min.css" rel="stylesheet" />
    <script src="~/validation/validation.js"></script>
</head>
<body>
    @if (TempData["ErrorMessage"] != null)
    {
        <h1 style="color:red; display: flex; justify-content: center;">
            @TempData["ErrorMessage"]
        </h1>
    }

    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-4" style="box-shadow: 1px 11px 10px 10px rgba(6, 8, 10, 0.05);">
            <form asp-action="Add" asp-controller="AppetizerManagement" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label for="CategoryID">Category</label>
                    <select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="AppetizerName" class="control-label"></label>
                    <input asp-for="AppetizerName" class="form-control" type="text" placeholder="Appetizer Name" id="Name" data-Err-Name="spnErrName" data-msg="Enter your Appetizer Name correctly" oninput="ValidationName(this)" />
                    <span class="text-danger" id="spnErrName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UnitPrice" class="control-label"></label>
                    <input asp-for="UnitPrice" class="form-control" type="text" placeholder="UnitPrice" id="UnitPrice" data-Err-UnitPrice="spnErrUnitPrice" data-msg="Enter your UnitPrice correctly" oninput="ValidationUnitPrice(this)" />
                    <span class="text-danger" id="spnErrUnitPrice"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SmallDescription" class="control-label"></label>
                    <input asp-for="SmallDescription" class="form-control" type="text" placeholder="Small Description" id="SmallDescription" data-Err-SmallDescription="spnErrSmallDescription" data-msg="Enter your Small Description correctly" oninput="ValidationSmallDescription(this)" />
                    <span class="text-danger" id="spnErrSmallDescription"></span>
                </div>
                <div class="form-group">
                    <span>Picture</span>
                    <input type="file" name="Picture" id="Picture" value="" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
</body>
</html>

ResturanShemronKabab/Views/AppetizerManagement/Index.cshtml
@model Restaurant.DomainModel.ApplicationModel.Appetizer.AppetizerSearchModel
@{
	SelectList categoryDropDown = (SelectList)ViewBag.categoryDropDown;
}
<form asp-controller="AppetizerManagement" asp-action="Index" method="get" id="frmSearch">
	<table class="table table-hover table-striped table-sm">
		<tr>
			<td>
				<label asp-for="AppetizerName" class="form-control"></label>
				<input type="text" class="form-control" asp-for="AppetizerName" />
			</td>
		</tr>
		<tr>
			<td>
				<label asp-for="CategoryID" class="form-control">Category</label>
				<select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
			</td>
		</tr>
		<tr>
			<td>
				<label asp-for="UnitPriceFrom" class="form-control"></label>
				<input type="text" class="form-control" asp-for="UnitPriceFrom" />
			</td>
		</tr>
		<tr>
			<td>
				<label asp-for="UnitPriceTo" class="form-control"></label>
				<input type="text" class="form-control" asp-for="UnitPriceTo" />
			</td>
		</tr>
		<tr class="text-center">
			<td colspan="2">
				<span class="btn btn-primary btn-sm spnSearch" data-controller="AppetizerManagement" data-action="Search">Search</span>
				@Html.ActionLink("RemoveFilter", "Index", "AppetizerManagement", null, new { @class = "btn btn-danger btn-sm" })
			</td>
		</tr>
	</table>
</form>

<div class="col-md-12">
	<a asp-action="Add" asp-controller="AppetizerManagement" class="btn btn-primary">Add New Food</a>
</div>



<div id="dvContent" data-controller="AppetizerManagement" data-action="List" data-search-form="frmSearch"></div>

ResturanShemronKabab/Views/AppetizerManagement/List.cshtml
@{
	Layout = null;
}
@model IEnumerable<Restaurant.DomainModel.ApplicationModel.Appetizer.AppetizerListItem>
<table class="table table-bordered table-hover table-striped ">
	<thead>
		<tr>
			<th>Appetizer ID</th>
			<th>Appetizer Name</th>
			<th>Category Name</th>
			<th>Unit Price</th>
			<th>Image</th>
			<th>Delete Image</th>
			<th>Delete</th>
			<th>Update</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var item in Model)
		{
			<tr id="tr-@item.AppetizerID">
				<td>
					@Html.DisplayFor(modelItem => item.AppetizerID)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.AppetizerName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.CategoryName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.UnitPrice)
				</td>
				<td style="display: flex; justify-content: center;">
					<img  src='@Url.Content(@item.Image)' width="100" />
				</td>
			@* 	<td>
					<span class="btn btn-warning btn-sm" onclick="DeleteImage('@item.AppetizerID')">Delete Image</span>
				</td> *@
				<td>
					<span class="btn btn-warning btn-sm" onclick="DeleteItem('@item.AppetizerID', 'AppetizerManagement', 'List', 'appetizerID', 'DeleteImage')">Delete Image</span>
				</td>
				<td>
					<span class="btn btn-danger btn-sm btn-Remove" data-controller="AppetizerManagement" data-action="Remove" data-id="@item.AppetizerID">Delete</span>
				</td>
				<td>
					@Html.ActionLink("Update", "Update", new { AppetizerID = item.AppetizerID }, new { @class = "btn btn-primary btn-sm" })
				</td>
			</tr>
		}
	</tbody>
</table>

ResturanShemronKabab/Views/AppetizerManagement/ListUI.cshtml
@{
	Layout = null;
}
@model IEnumerable<Restaurant.DomainModel.ApplicationModel.Appetizer.AppetizerListItemUI>
<div class="ContainerAll">
	@foreach (var item in Model)
	{
		<div class="ContainerOne">
			<div class="ListBox">
				<img src='@Url.Content(@item.Image)' />
				<h1>@Html.DisplayFor(modelItem => item.AppetizerName)</h1>
				<p>@Html.DisplayFor(modelItem => item.UnitPrice)</p>
				<p class="TextTooman">تومان</p>
			</div>
		</div>
	}
</div>

ResturanShemronKabab/Views/AppetizerManagement/Update.cshtml
@model ResturanShemronKabab.ViewModel.AppetizerDetailsModel
@{
	Layout = null;
	SelectList categoryDropDown = (SelectList)ViewBag.categoryDropDown;
}
<h4 style="display: flex;
    justify-content: center;
    margin-right: 60px;">
	Update Food
</h4>
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Add</title>
	<link href="~/content/font-awesome.css" rel="stylesheet" />
	<link href="~/content/font-awesome.min.css" rel="stylesheet" />
	<link href="~/css/stylesheet.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ResturanShemronKabab.styles.css" asp-append-version="true" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<link href="~/css/sweetalert2.min.css" rel="stylesheet" />
	<script src="~/validation/validation.js"></script>
</head>
<body>
	@if (TempData["ErrorMessage"] != null)
	{
		<h1 style="color:red">@TempData["ErrorMessage"]</h1>
	}

	<div class="row" style="    display: flex;
    justify-content: center;">
		<div class="col-md-4" style="    box-shadow: 1px 11px 10px 10px rgba(6, 8, 10, 0.05);">
			<form asp-action="Update" asp-controller="AppetizerManagement" method="post" enctype="multipart/form-data">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">

					<input type="hidden" asp-for="AppetizerID" class="form-control" />

				</div>
				<div class="form-group">
					<label for="CategoryID">Category</label>
					<select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
				</div>
				<div class="form-group">
					<label asp-for="AppetizerName" class="control-label"></label>
					<input asp-for="AppetizerName" class="form-control" type="text" placeholder="Food Name" id="Name" data-Err-Name="spnErrName" data-msg="Enter your Food Name correctly" oninput="ValidationName(this)" />
					<span class="text-danger" id="spnErrName"></span>
				</div>
				<div class="form-group">
					<label asp-for="UnitPrice" class="control-label"></label>
					<input asp-for="UnitPrice" class="form-control" type="text" placeholder="UnitPrice" id="UnitPrice" data-Err-UnitPrice="spnErrUnitPrice" data-msg="Enter your UnitPrice correctly" oninput="ValidationUnitPrice(this)" />
					<span class="text-danger" id="spnErrUnitPrice"></span>
				</div>
				<div class="form-group">
					<label asp-for="SmallDescription" class="control-label"></label>
					<input asp-for="SmallDescription" class="form-control" type="text" placeholder="Small Description" id="SmallDescription" data-Err-SmallDescription="spnErrSmallDescription" data-msg="Enter your Small Description correctly" oninput="ValidationSmallDescription(this)" />
					<span class="text-danger" id="spnErrSmallDescription"></span>
				</div>
				<div class="form-group">
					<span> Your Old Image is : </span>
					<img src="@Url.Content(Model.ImageURl)" width="200" />
				</div>
				<div class="form-group">
					<span> Select a new Image If Image Must Change</span>
					<input type="file" name="Picture" id="Picture" value="" />
				</div>
				<div class="form-group">
					<input type="submit" value="Update" class="btn btn-success .btn-updateFood" />
					<a href="Index" class="btn btn-primary">Cancel</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>