ResturanShemronKabab/Controllers/BeveragesManagementController.cs
using FrameWork;
using FrameWork.DTOS;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing.Constraints;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Restaurant.Application;
using Restaurant.ApplicationServiceContract.Services;
using Restaurant.DomainModel.ApplicationModel.Appetizer;
using Restaurant.DomainModel.ApplicationModel.Beverages;
using Restaurant.DomainModel.ApplicationModel.Category;
using Restaurant.DomainModel.ApplicationModel.Food;
using Restaurant.DomainModel.Models;
using ResturanShemronKabab.ViewModel;

namespace ResturanShemronKabab.Controllers
{
	public class BeveragesManagementController : Controller
	{
		private readonly IBeveragesApplication beveragesApplication;
		private readonly ICategoryApplication categoryApplication;
		private readonly IHostEnvironment env;
		public BeveragesManagementController(IBeveragesApplication beveragesApplication, ICategoryApplication categoryApplication, IHostEnvironment env)
		{
			this.categoryApplication = categoryApplication;
			this.beveragesApplication = beveragesApplication;
			this.env = env;
		}

		private void InflateCategoryDrp()
		{
			var Cat = categoryApplication.GetDrp();
			Cat.Insert(0, new CategoryListForDrp { CategoryID = -1, CategoryName = "...Please Select..." });
			SelectList categoryDropDown = new SelectList(Cat, "CategoryID", "CategoryName");
			ViewBag.categoryDropDown = categoryDropDown;
		}

		public IActionResult Index(BeveragesSearchModel sm)
		{
			InflateCategoryDrp();
			return View(sm);
		}

		public IActionResult List()
		{
			var beverages = beveragesApplication.GetAllListItem();
			return View(beverages);
		}

		public IActionResult ListUI()
		{
			var beve = beveragesApplication.GetAllListItemInUI();
			return View(beve);
		}

		public IActionResult Add()
		{
			InflateCategoryDrp();
			return View();
		}
		[HttpPost]
		public IActionResult Add(BeveragesAddEditViewModel model)
		{
            if (model.Picture == null)
            {
                InflateCategoryDrp();
                TempData["ErrorMessage"] = "Please select the food";
                return View(model);
            }
            string PhisycalAddress = Path.GetFileName(model.Picture.FileName).ToUniqueFileName();
			string Relativeaddress = @"~/Images/" + PhisycalAddress;
			PhisycalAddress = env.ContentRootPath + @"\wwwroot\Images\" + PhisycalAddress;
			FileStream fs = new FileStream(PhisycalAddress, FileMode.Create);
			{
				model.Picture.CopyTo(fs);
			};
			BeveragesAddAndEditModel beveragesAddAndEditModel = new BeveragesAddAndEditModel
			{
				ImageURL = Relativeaddress,
				UnitPrice = model.UnitPrice,
				BeveragesID = model.BeveragesID,
				BeveragesName = model.BeveragesName,
				CategoryID = model.CategoryID,
			};
			var op = beveragesApplication.Register(beveragesAddAndEditModel);
            if (!op.Success)
            {
                InflateCategoryDrp();
                TempData["ErrorMessage"] = op.Message;
                return View(model);
            }
            return RedirectToAction("index");
        }


		[HttpPost]
		public JsonResult Remove(int id)
		{
			//var beverages = beveragesApplication.Get(id);
			//if (!string.IsNullOrEmpty(beverages.ImageURL))
			//{
			//	var url = env.ContentRootPath + @"\wwwroot" + beverages.ImageURL.Substring(1, beverages.ImageURL.Length - 1).Replace(@"/", @"\");
			//	if (System.IO.File.Exists(url))
			//	{
			//		System.IO.File.Delete(url);
			//	}
			//}
			var op = beveragesApplication.Remove(id);
			return Json(op);
		}

		public IActionResult Update(int beveragesID)
		{
			var n = beveragesApplication.Get(beveragesID);
			InflateCategoryDrp();
			var beverages = new BeveragesDetailsModel
			{
				BeveragesID = beveragesID,
				BeveragesName = n.BeveragesName,
				UnitPrice = n.UnitPrice,
				ImageURL = n.ImageURL,
				CategoryID = n.CategoryID,
			};
			return View(beverages);
		}

		[HttpPost]
		public IActionResult Update(BeveragesAddEditViewModel model)
		{
			var oldBeverages = beveragesApplication.Get(model.BeveragesID);
			if (model.Picture == null)
			{
				BeveragesAddAndEditModel NewBeverages = new BeveragesAddAndEditModel
				{
					ImageURL = oldBeverages.ImageURL,
					BeveragesID = model.BeveragesID,
					CategoryID = model.CategoryID,
					UnitPrice = model.UnitPrice,
					BeveragesName = model.BeveragesName,
				};
				var opExist = beveragesApplication.Update(NewBeverages);
				var beverages = new BeveragesDetailsModel
				{
					BeveragesID = oldBeverages.BeveragesID,
					ImageURL = oldBeverages.ImageURL,
					BeveragesName = oldBeverages.BeveragesName,
					UnitPrice = oldBeverages.UnitPrice,
					CategoryID = oldBeverages.CategoryID,
				};
				if (!opExist.Success)
				{
					InflateCategoryDrp();
					TempData["ErrorMessage"] = opExist.Message;
					return View(beverages);
				}
				return RedirectToAction("Index");
			}

			else//agar ax bood
			{

				if (!string.IsNullOrEmpty(oldBeverages.ImageURL) && oldBeverages.ImageURL.ToLower() != "~/images/noimage.png")
				{
					var url = env.ContentRootPath + @"\wwwroot" + oldBeverages.ImageURL.Substring(1, oldBeverages.ImageURL.Length - 1).Replace(@"/", @"\");
					if (System.IO.File.Exists(url))
					{
						System.IO.File.Delete(url);
					}
				}
				string PhisycalAddress = Path.GetFileName(model.Picture.FileName);
				string Relativeaddress = @"~/Images/" + PhisycalAddress;
				PhisycalAddress = env.ContentRootPath + @"\wwwroot\Images\" + PhisycalAddress;
				using (FileStream fs = new FileStream(PhisycalAddress, FileMode.Create))
				{
					model.Picture.CopyTo(fs);
				}
				BeveragesAddAndEditModel n = new BeveragesAddAndEditModel
				{
					BeveragesID = model.BeveragesID,
					ImageURL = Relativeaddress,
					BeveragesName = model.BeveragesName,
					CategoryID = model.CategoryID,
					UnitPrice = model.UnitPrice,
				};
				var op = beveragesApplication.Update(n);
				var food = new BeveragesDetailsModel
				{
					BeveragesID = oldBeverages.BeveragesID,
					BeveragesName = oldBeverages.BeveragesName,
					CategoryID = oldBeverages.CategoryID,
					ImageURL = oldBeverages.ImageURL,
					UnitPrice = oldBeverages.UnitPrice,
				};
				if (op.Success)
				{
					return RedirectToAction("index");

				}
				else
				{
					InflateCategoryDrp();
					TempData["ErrorMessage"] = op.Message;
					return View(food);
				}

			}
		}

		public IActionResult Search(BeveragesSearchModel sm)
		{
			var beverages = beveragesApplication.Search(sm, out int recordCount);
			return PartialView("List", beverages);
		}

		[HttpPost]
		public JsonResult RemoveImage(int beveragesID)
		{
			var oldBeverages = beveragesApplication.Get(beveragesID);
			if (oldBeverages == null && !string.IsNullOrEmpty(oldBeverages.ImageURL) && oldBeverages.ImageURL != @"~/images/noimage.png")
			{
				var url = Path.Combine(env.ContentRootPath, "wwwroot", oldBeverages.ImageURL.Substring(1).Replace("/", "\\"));
				if (System.IO.File.Exists(url))
				{
					System.IO.File.Delete(url);
				}
			}
			OperationResult op = new OperationResult("Delete Image ");
			try
			{
				beveragesApplication.RemoveImage(beveragesID);
				return Json(op.ToSuccess("Delete Image Success Fully"));
			}
			catch(Exception ex)
			{
				return Json(op.ToFail("Delete Image Failed " + ex.Message));
			}
		}
	}
}

ResturanShemronKabab/Views/BeveragesManagement/Add.cshtml
@model ResturanShemronKabab.ViewModel.BeveragesAddEditViewModel
@{
	Layout = null;
	SelectList categoryDropDown = (SelectList)ViewBag.categoryDropDown;
}

<h4 style="display: flex; justify-content: center; margin-right: 60px;">
    Update Food
</h4>
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <link href="~/content/font-awesome.css" rel="stylesheet" />
    <link href="~/content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/stylesheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ResturanShemronKabab.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="~/css/sweetalert2.min.css" rel="stylesheet" />
    <script src="~/validation/validation.js"></script>
</head>
<body>
    @if (TempData["ErrorMessage"] != null)
    {
        <h1 style="color:red; display: flex; justify-content: center;">
            @TempData["ErrorMessage"]
        </h1>
    }

    <div class="row" style="display: flex; justify-content: center;">
        <div class="col-md-4" style="box-shadow: 1px 11px 10px 10px rgba(6, 8, 10, 0.05);">
			<form asp-action="Add" asp-controller="BeveragesManagement" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label for="CategoryID">Category</label>
					<select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
				</div>
				<div class="form-group">
					<label asp-for="BeveragesName" class="control-label"></label>
					<input asp-for="BeveragesName" class="form-control" type="text" placeholder="Beverages Name" id="Name" data-Err-Name="spnErrName" data-msg="Enter your Beverages Name correctly" oninput="ValidationName(this)" />
					<span class="text-danger" id="spnErrName"></span>
				</div>
				<div class="form-group">
					<label asp-for="UnitPrice" class="control-label"></label>
					<input asp-for="UnitPrice" class="form-control" type="text" placeholder="UnitPrice" id="UnitPrice" data-Err-UnitPrice="spnErrUnitPrice" data-msg="Enter your UnitPrice correctly" oninput="ValidationUnitPrice(this)" />
					<span class="text-danger" id="spnErrUnitPrice"></span>
				</div>
				<div class="form-group">
					<span>Picture</span>
					<input type="file" name="Picture" id="Picture" value="" />
				</div>
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-success" />
				</div>
            </form>
        </div>
    </div>
</body>
</html>

ResturanShemronKabab/Views/BeveragesManagement/Index.cshtml
@model Restaurant.DomainModel.ApplicationModel.Beverages.BeveragesSearchModel
@{
	SelectList categoryDropDown = (SelectList)ViewBag.categoryDropDown;
}
<form asp-controller="BeveragesManagement" asp-action="Index" method="get" id="frmSearch">
	<table class="table table-hover table-striped table-sm">
		<tr>
			<td>
				<label asp-for="BeveragesName" class="form-control"></label>
				<input type="text" class="form-control" asp-for="BeveragesName" />
			</td>
		</tr>
		<tr>
			<td>
				<label asp-for="CategoryID" class="form-control">Category</label>
				<select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
			</td>
		</tr>
		<tr>
			<td>
				<label asp-for="UnitPriceFrom" class="form-control"></label>
				<input type="text" class="form-control" asp-for="UnitPriceFrom" />
			</td>
		</tr>
		<tr>
			<td>
				<label asp-for="UnitPriceTo" class="form-control"></label>
				<input type="text" class="form-control" asp-for="UnitPriceTo" />
			</td>
		</tr>
		<tr class="text-center">
			<td colspan="2">
				<span class="btn btn-primary btn-sm spnSearch" data-controller="BeveragesManagement" data-action="Search">Search</span>
				@Html.ActionLink("RemoveFilter", "Index", "BeveragesManagement", null, new { @class = "btn btn-danger btn-sm" })
			</td>
		</tr>
	</table>
</form>

<div class="col-md-12">
	<a asp-action="Add" asp-controller="BeveragesManagement" class="btn btn-primary">Add New Food</a>
</div>


<div id="dvContent" data-controller="BeveragesManagement" data-action="List" data-search-form="frmSearch"></div>

ResturanShemronKabab/Views/BeveragesManagement/List.cshtml
@{
	Layout = null;
}
@model IEnumerable<Restaurant.DomainModel.ApplicationModel.Beverages.BeveragesListItem>
<table class="table table-bordered table-hover table-striped ">
	<thead>
		<tr>
			<th>Beverages ID</th>

			<th>Category Name</th>

			<th>Beverages Name</th>

			<th>Unit Price</th>

			<th>Image</th>

			<th>Delete Image</th>

			<th>Delete</th>

			<th>Update</th>

		</tr>
	</thead>
	<tbody>
		@foreach(var item in Model)
		{
			<tr id="tr-@item.BeveragesID">

				<td>@Html.DisplayFor(modelItem => item.BeveragesID)</td>

				<td>@Html.DisplayFor(modelItem => item.CategoryName)</td>

				<td>@Html.DisplayFor(modelItem => item.BeveragesName)</td>

				<td>@Html.DisplayFor(modelItem => item.UnitPrice)</td>

				<td style="display: flex; justify-content: center;">
					<img src='@Url.Content(@item.Image)' width="100" />
				</td>

				<td>
					<span class="btn btn-warning btn-sm" onclick="DeleteItem('@item.BeveragesID', 'BeveragesManagement', 'List', 'beveragesID', 'RemoveImage')">Delete Image</span>


				</td>

				<td>
					<span class="btn btn-danger btn-sm btn-Remove" data-controller="BeveragesManagement" data-action="Remove" data-id="@item.BeveragesID">Delete</span>
				</td>
				<td>
					@Html.ActionLink("Update", "Update", new { BeveragesID = item.BeveragesID }, new { @class = "btn btn-primary btn-sm" })
				</td>
				
			</tr>
		}

	</tbody>
</table>

ResturanShemronKabab/Views/BeveragesManagement/ListUI.cshtml
@{
	Layout = null;
}
@model IEnumerable<Restaurant.DomainModel.ApplicationModel.Beverages.BeveragesListItemUI>
<div class="ContainerAll">
	@foreach (var item in Model)
	{
		<div class="ContainerOne">
			<div class="ListBox">
				<img src='@Url.Content(@item.Image)' />
				<h1>@Html.DisplayFor(modelItem => item.BeveragesName)</h1>
				<p>@Html.DisplayFor(modelItem => item.UnitPrice)</p>
				<p class="TextTooman">تومان</p>
			</div>
		</div>
	}
</div>

ResturanShemronKabab/Views/BeveragesManagement/Update.cshtml
@model ResturanShemronKabab.ViewModel.BeveragesDetailsModel
@{
	Layout = null;
	SelectList categoryDropDown = (SelectList)ViewBag.categoryDropDown;
}
<h4 style="display: flex;
    justify-content: center;
    margin-right: 60px;">
	Update Food
</h4>
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Add</title>
	<link href="~/content/font-awesome.css" rel="stylesheet" />
	<link href="~/content/font-awesome.min.css" rel="stylesheet" />
	<link href="~/css/stylesheet.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ResturanShemronKabab.styles.css" asp-append-version="true" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<link href="~/css/sweetalert2.min.css" rel="stylesheet" />
	<script src="~/validation/validation.js"></script>
</head>
<body>
	@if (TempData["ErrorMessage"] != null)
	{
		<h1 style="color:red">@TempData["ErrorMessage"]</h1>
	}

	<div class="row" style="    display: flex;
    justify-content: center;">
		<div class="col-md-4" style="    box-shadow: 1px 11px 10px 10px rgba(6, 8, 10, 0.05);">
			<form asp-action="Update" asp-controller="BeveragesManagement" method="post" enctype="multipart/form-data">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">

					<input type="hidden" asp-for="BeveragesID" class="form-control" />

				</div>
				<div class="form-group">
					<label for="CategoryID">Category</label>
					<select asp-items="categoryDropDown" class="form-control" asp-for="CategoryID"></select>
				</div>
				<div class="form-group">
					<label asp-for="BeveragesName" class="control-label"></label>
					<input asp-for="BeveragesName" class="form-control" type="text" placeholder="Food Name" id="Name" data-Err-Name="spnErrName" data-msg="Enter your Food Name correctly" oninput="ValidationName(this)" />
					<span class="text-danger" id="spnErrName"></span>
				</div>
				<div class="form-group">
					<label asp-for="UnitPrice" class="control-label"></label>
					<input asp-for="UnitPrice" class="form-control" type="text" placeholder="UnitPrice" id="UnitPrice" data-Err-UnitPrice="spnErrUnitPrice" data-msg="Enter your UnitPrice correctly" oninput="ValidationUnitPrice(this)" />
					<span class="text-danger" id="spnErrUnitPrice"></span>
				</div>
				<div class="form-group">
					<span> Your Old Image is : </span>
					<img src="@Url.Content(Model.ImageURL)" width="200" />
				</div>
				<div class="form-group">
					<span> Select a new Image If Image Must Change</span>
					<input type="file" name="Picture" id="Picture" value="" />
				</div>
				<div class="form-group">
					<input type="submit" value="Update" class="btn btn-success .btn-updateFood" />
					<a href="Index" class="btn btn-primary">Cancel</a>
				</div>
			</form>
		</div>
	</div>
</body>
</html>