ResturanShemronKabab/Controllers/CategoryManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Restaurant.ApplicationServiceContract.Services;
using Restaurant.DomainModel.ApplicationModel.Category;

namespace ResturanShemronKabab.Controllers
{
	public class CategoryManagementController : Controller
	{
		private readonly ICategoryApplication CatApplication;

		public CategoryManagementController(ICategoryApplication CatApplication)
		{
			this.CatApplication = CatApplication;
		}

		private void BindRoods()
		{
			var cats = CatApplication.GetRoots();
			cats.Insert(0, new CategoryListItem { CategoryName = "ادسته اصلی" });
			ViewBag.drpRoots = new SelectList(cats, "CategoryID", "CategoryName");
		}

		public IActionResult Index(CategorySearchModel sm)
		{
			return View(sm);
		}

		public IActionResult List()
		{
			var Cats = CatApplication.GetAllListItem();
			return View(Cats);
		}

		public IActionResult Add()
		{
			BindRoods();
			return View();
		}

		[HttpPost]
		public JsonResult Add(CategoryAddAndEditModel model)
		{
			if (model.ParentID == 0)
			{
				model.ParentID = null;
			}
			var op = CatApplication.Register(model);
			return Json(op);
		}

		[HttpPost]
		public JsonResult Delete(int id)
		{
			var op = CatApplication.Remove(id);
			return Json(op);
		}

		public IActionResult Update(int id)
		{
			BindRoods();
			var cat = CatApplication.Get(id);
			return View(cat);
		}
		[HttpPost]
		public JsonResult Update (CategoryAddAndEditModel model)
		{
			var op = CatApplication.Update(model);
			return Json(op);
		}

		public IActionResult Search (CategorySearchModel searchModel)
		{
			var cat = CatApplication.Search(searchModel, out int recordCount);
			return PartialView("List", cat);
		}
	}
}

ResturanShemronKabab/Controllers/EmployeeManagementController.cs
using FrameWork.DTOS;
using Microsoft.AspNetCore.Mvc;
using Restaurant.ApplicationServiceContract.Services;
using Restaurant.DomainModel.ApplicationModel.Employee;
using ResturanShemronKabab.Helper;

namespace ResturanShemronKabab.Controllers
{
    public class EmployeeManagementController : Controller
    {
        private readonly IEmployeeApplication employeeApplication;
        private readonly IWebHostEnvironment env;

        public EmployeeManagementController(IEmployeeApplication employeeApplication, IWebHostEnvironment env)
        {
            this.employeeApplication = employeeApplication;
            this.env = env;
        }
        public IActionResult Index(EmployeeSearchModel sm)
        {
            return View(sm);
        }
        public IActionResult List()
        {
            var emp = employeeApplication.GetAllListItem();
            return View(emp);
        }
        [HttpPost]
        public JsonResult Remove(int ID)
        {
            var op = employeeApplication.Remove(ID);
            return Json(op);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Add(EmployeeAddAndEditModel model)
        {
            var op = employeeApplication.Register(model);
            return Json(op);
        }

        public IActionResult Update(int id)
        {

            var cat = employeeApplication.Get(id);
            return View(cat);
        }
        [HttpPost]
        public JsonResult Update(EmployeeAddAndEditModel emp)
        {
            var op = employeeApplication.Update(emp);
            return Json(op);
        }

        public IActionResult Search(EmployeeSearchModel sm)
        {
            var emp = employeeApplication.Search(sm, out var recordCount);
            return PartialView("List", emp);
        }
    }
}

ResturanShemronKabab/Controllers/FoodManagementController.cs
using FrameWork;
using FrameWork.DTOS;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.Identity.Client;
using Restaurant.Application;
using Restaurant.ApplicationServiceContract.Services;
using Restaurant.DataAccessServiceContract.Repositories;
using Restaurant.DomainModel.ApplicationModel.Category;
using Restaurant.DomainModel.ApplicationModel.Food;
using Restaurant.DomainModel.Models;
using ResturanShemronKabab.Framwork.UI.Services;
using ResturanShemronKabab.ViewModel;
using System.Net.NetworkInformation;

namespace ResturanShemronKabab.Controllers
{
	public class FoodManagementController : Controller
	{
		private readonly IFoodApplication foodApplication;

		private readonly ICategoryApplication categoryApplication;

		private readonly IHostEnvironment env;

		public FoodManagementController(IFoodApplication foodApplication, ICategoryApplication categoryApplication, IHostEnvironment env)
		{
			this.foodApplication = foodApplication;
			this.categoryApplication = categoryApplication;
			this.env = env;
		}

		private void InflateCategoryDrp()
		{
			var Cat = categoryApplication.GetDrp();
			Cat.Insert(0, new CategoryListForDrp { CategoryID = -1, CategoryName = "...Please Select..." });
			SelectList categoryDropDown = new SelectList(Cat, "CategoryID", "CategoryName");
			ViewBag.categoryDropDown = categoryDropDown;
		}

		public IActionResult Index(FoodSearchModel sm)
		{
			InflateCategoryDrp();
			return View(sm);
		}

		public IActionResult List()
		{
			var food = foodApplication.GetAllListItem();
			return View(food);
		}

		public IActionResult ListUI()
		{
			var food = foodApplication.GetAllListItemInUI();
			return View(food);
		}

		public IActionResult Add()
		{
			InflateCategoryDrp();
			return View();
		}
		[HttpPost]
		public IActionResult Add(FoodAddEditViewModel model)
		{
			if(model.Picture == null)
			{
				InflateCategoryDrp();
				TempData["ErrorMessage"] = "Please select the food";
                return View(model);
            }
			string PhisycalAddress = Path.GetFileName(model.Picture.FileName);
			string Relativeaddress = @"~/Images/" + PhisycalAddress;
			PhisycalAddress = env.ContentRootPath + @"\wwwroot\Images\" + PhisycalAddress;
			using (FileStream fs = new FileStream(PhisycalAddress, FileMode.Create))
			{
				model.Picture.CopyTo(fs);
			}
			FoodAddAndEditModel foodAddAndEditModel = new FoodAddAndEditModel
			{
				ImageURL = Relativeaddress,
				FoodName = model.FoodName,
				CategoryID = model.CategoryID,
				Materials = model.Materials,
				UnitPrice = model.UnitPrice,
				FoodID = model.FoodID,
			};
			var op = foodApplication.Register(foodAddAndEditModel);
			if (!op.Success)
			{
                InflateCategoryDrp();
				TempData["ErrorMessage"] = op.Message;
				return View(model);
			}
			return RedirectToAction("index");
		}

		[HttpPost]
		public JsonResult Remove(int ID)
		{
			//         var food = foodApplication.Get(ID);
			//if (!string.IsNullOrEmpty(food.ImageURL))
			//{
			//	var url = env.ContentRootPath + @"\wwwroot" + food.ImageURL.Substring(1, food.ImageURL.Length - 1).Replace(@"/", @"\");
			//	if (System.IO.File.Exists(url))
			//	{
			//		System.IO.File.Delete(url);
			//	}
			//}
			var op = foodApplication.Remove(ID);
			return Json(op);
		}

		public IActionResult Search(FoodSearchModel sm)
		{
			var food = foodApplication.Search(sm, out int recordCount);
			return PartialView("List", food);
		}

		[HttpPost]
		public JsonResult DeleteImage(int foodID)
		{
			var n = foodApplication.Get(foodID);
			if (n != null && !string.IsNullOrEmpty(n.ImageURL) && n.ImageURL.ToLower() != @"~/images/noimage.png")
			{
				var url = Path.Combine(env.ContentRootPath, "wwwroot", n.ImageURL.Substring(1).Replace("/", "\\"));
				if (System.IO.File.Exists(url))
				{
					System.IO.File.Delete(url);
				}
			}
			OperationResult op = new OperationResult("Delete Image");
			try
			{
				foodApplication.RemoveImage(foodID);
				return Json(op.ToSuccess("Image Removed"));
			}
			catch (Exception)
			{
				return Json(op.ToFail("Image did not Removed"));
			}
		}

		public IActionResult Update(int foodID)
		{
			var n = foodApplication.Get(foodID);
			InflateCategoryDrp();
			var food = new FoodDetailsModel
			{
				FoodID = foodID,
				FoodName = n.FoodName,
				CategoryID = n.CategoryID,
				ImageURL = n.ImageURL,
				Materials = n.Materials,
				UnitPrice = n.UnitPrice,
			};
			return View(food);
		}

		[HttpPost]
		public IActionResult Update(FoodAddEditViewModel model)
		{
			var oldFood = foodApplication.Get(model.FoodID);
			if (model.Picture == null)
			{
				FoodAddAndEditModel NewFood = new FoodAddAndEditModel
				{
					FoodID = model.FoodID,
					ImageURL = oldFood.ImageURL,
					FoodName = model.FoodName,
					CategoryID = model.CategoryID,
					Materials = model.Materials,
					UnitPrice = model.UnitPrice,
				};
				var opExist = foodApplication.Update(NewFood);
				var food = new FoodDetailsModel
				{
					FoodID = oldFood.FoodID,
					FoodName = oldFood.FoodName,
					CategoryID = oldFood.CategoryID,
					ImageURL = oldFood.ImageURL,
					Materials = oldFood.Materials,
					UnitPrice = oldFood.UnitPrice,
				};
				if (!opExist.Success)
				{
					InflateCategoryDrp();
					TempData["ErrorMessage"] = opExist.Message;
					return View(food);
				}
				return RedirectToAction("Index");
			}

			else//agar ax bood
			{

				if (!string.IsNullOrEmpty(oldFood.ImageURL) && oldFood.ImageURL.ToLower() != "~/images/noimage.png")
				{
					var url = env.ContentRootPath + @"\wwwroot" + oldFood.ImageURL.Substring(1, oldFood.ImageURL.Length - 1).Replace(@"/", @"\");
					if (System.IO.File.Exists(url))
					{
						System.IO.File.Delete(url);
					}
				}
				string PhisycalAddress = Path.GetFileName(model.Picture.FileName);
				string Relativeaddress = @"~/Images/" + PhisycalAddress;
				PhisycalAddress = env.ContentRootPath + @"\wwwroot\Images\" + PhisycalAddress;
				using (FileStream fs = new FileStream(PhisycalAddress, FileMode.Create))
				{
					 model.Picture.CopyTo(fs);
				}
				FoodAddAndEditModel n = new FoodAddAndEditModel
				{
					FoodID = model.FoodID,
					ImageURL = Relativeaddress,
					FoodName = model.FoodName,
					CategoryID = model.CategoryID,
					Materials = model.Materials,
					UnitPrice = model.UnitPrice,
				};
				var op = foodApplication.Update(n);
				var food = new FoodDetailsModel
				{
					FoodID = oldFood.FoodID,
					FoodName = oldFood.FoodName,
					CategoryID = oldFood.CategoryID,
					ImageURL = oldFood.ImageURL,
					Materials = oldFood.Materials,
					UnitPrice = oldFood.UnitPrice,
				};
				if (op.Success)
				{
					return RedirectToAction("index");

				}
				else
				{
					InflateCategoryDrp();
					TempData["ErrorMessage"] = op.Message;
					return View(food);
				}

			}
		}
	}
}

ResturanShemronKabab/Controllers/UserManagementController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Application;
using Restaurant.ApplicationServiceContract.Services;
using Restaurant.DomainModel.ApplicationModel.Food;
using Restaurant.DomainModel.ApplicationModel.User;

namespace ResturanShemronKabab.Controllers
{
	public class UserManagementController : Controller
	{
		private readonly IUserApplication userApplication;
        public UserManagementController(IUserApplication userApplication)
        {
            this.userApplication = userApplication;
        }
        public IActionResult Index(UserSearchModel sm)
		{
			return View(sm);
		}
		public IActionResult List()
		{
			var user = userApplication.GetAllListItem();
			return View(user);
		}
		public IActionResult Search(UserSearchModel sm)
		{
			var user = userApplication.Search(sm, out int recordCount);
			return PartialView("List", user);
		}
		public IActionResult Add()
		{
			return View();
		}
		[HttpPost]
		public JsonResult Add(UserAddAndEditModel model)
		{
			if(model.RoleID == 0)
			{
				model.RoleID = 2;
			}
			var op = userApplication.Register(model);
			return Json(op);
		}
		[HttpPost]
		public JsonResult Remove(int ID)
		{
			var op = userApplication.Delete(ID);
			return Json(op);
		}
		public IActionResult Update(int id)
		{
			var user = userApplication.Get(id);
			return View(user);
		}
		[HttpPost]
		public JsonResult Update(UserAddAndEditModel model)
		{
			if (model.RoleID == 0)
			{
				model.RoleID = 2;
			}
			var op = userApplication.Update(model);
			return Json(op);
		}

	}
}

ResturanShemronKabab/Views/Shared/LayoutSite.cshtml
<script>
	function BindGrid() {
		let action = $("#dvContent").attr("data-action");
		let controller = $("#dvContent").attr("data-controller");
		let sendingUrl = `/${controller}/${action}`;
		let sendingData = null;
		// $(".waiting").css("display", "flex");
		$.get(sendingUrl, sendingData, function (recevingData) {
			// $(".waiting").css("display", "none");
			$("#dvContent").html(recevingData);
		});
	}

	function BindGrid2() {
		let action = $("#dvContent2").attr("data-action");
		let controller = $("#dvContent2").attr("data-controller");
		let sendingUrl = `/${controller}/${action}`;
		let sendingData = null;
		// $(".waiting").css("display", "flex");
		$.get(sendingUrl, sendingData, function (recevingData) {
			// $(".waiting").css("display", "none");
			$("#dvContent2").html(recevingData);
		});
	}

	function BindGrid3() {
		let action = $("#dvContent3").attr("data-action");
		let controller = $("#dvContent3").attr("data-controller");
		let sendingUrl = `/${controller}/${action}`;
		let sendingData = null;
		// $(".waiting").css("display", "flex");
		$.get(sendingUrl, sendingData, function (recevingData) {
			// $(".waiting").css("display", "none");
			$("#dvContent3").html(recevingData);
		});
	}

	$(document).ready(function () {
		BindGrid();
		BindGrid2();
		BindGrid3();
	});
</script>

ResturanShemronKabab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ResturanShemronKabab</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ResturanShemronKabab.styles.css" asp-append-version="true" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<link href="~/css/sweetalert2.min.css" rel="stylesheet" />
	<script src="~/js/sweetalert2.min.js"></script>
	<script src="~/validation/validation.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ResturanShemronKabab</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="EmployeeManagement" asp-action="Index">Employee</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="FoodManagement" asp-action="Index">Food</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="AppetizerManagement" asp-action="Index">Appetizer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="BeveragesManagement" asp-action="Index">Beverages</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="CategoryManagement" asp-action="Index">Category</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="Index">User</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2024 - ResturanShemronKabab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>

	<!DOCTYPE html>
	<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<body>

		<script>

			function SuccessMessage(SuccessTxt) {
				Swal.fire({
					icon: 'success',
					title: 'با موفقیت انجام شد ',
					text: SuccessTxt,
				});
			}
			function ErrorMessage(ErrorTxt) {
				Swal.fire({
					icon: 'error',
					title: 'خطا',
					text: ErrorTxt,
				});
			}

			//BindGrid SSR
			function BindGrid() {
				let action = $("#dvContent").attr("data-action");
				let controller = $("#dvContent").attr("data-controller");
				let sendingUrl = `/${controller}/${action}`;
				let sendingData = null;
				// $(".waiting").css("display", "flex");
				$.get(sendingUrl, sendingData, function (recevingData) {
					// $(".waiting").css("display", "none");
					$("#dvContent").html(recevingData);
				});
			}

			function BindGrid2() {
				let action = $("#dvContent2").attr("data-action");
				let controller = $("#dvContent2").attr("data-controller");
				let sendingUrl = `/${controller}/${action}`;
				let sendingData = null;
				// $(".waiting").css("display", "flex");
				$.get(sendingUrl, sendingData, function (recevingData) {
					// $(".waiting").css("display", "none");
					$("#dvContent2").html(recevingData);
				});
			}

			function BindGrid3() {
				let action = $("#dvContent3").attr("data-action");
				let controller = $("#dvContent3").attr("data-controller");
				let sendingUrl = `/${controller}/${action}`;
				let sendingData = null;
				// $(".waiting").css("display", "flex");
				$.get(sendingUrl, sendingData, function (recevingData) {
					// $(".waiting").css("display", "none");
					$("#dvContent3").html(recevingData);
				});
			}

			$(document).ready(function () {
				BindGrid();
				BindGrid2();
				BindGrid3();
			});



			//Search

			$(document).on("click", ".spnSearch", function () {
				let action = $(this).attr("data-action");
				let controller = $(this).attr("data-controller");
				var sendingData = $("#frmSearch").serialize();
				var sendingUrl = `/${controller}/${action}`;
				$.get(sendingUrl, sendingData, function (partialSearch) {
					$("#dvContent").html(partialSearch);
				});
			});



			//Delete
			$(document).on("click", ".btn-Remove", function () {
				if (confirm("آیا مطمن هستید")) {
					let action = $(this).attr("data-action");
					let controller = $(this).attr("data-controller");
					let id = $(this).attr("data-id");
					let sendingUrl = `/${controller}/${action}`;
					let sendingData = `id=${id}`;
					//$(".waiting").css("display", "flex");
					$.post(sendingUrl, sendingData, function (operationResult) {
						if (operationResult.success.toString() == "true") {
							BindGrid();
							SuccessMessage(operationResult.message);
						}
						else {
							ErrorMessage(operationResult.message);
						}

					});
				}
			});


			// // //Delete Image
			// function DeleteImage(FoodID) {
			// 	debugger;
			// 	$.post("/FoodManagement/DeleteImage", { foodID: FoodID }, function (op) {
			// 		if (op.success) {
			// 			let action = "List";
			// 			let controller = "FoodManagement";
			// 			let sendingUrl = `/${controller}/${action}`;

			// 			$.get(sendingUrl, null, function (receivingData) {
			// 				$("#dvContent").html(receivingData);
			// 			});
			// 		} else {
			// 			alert(op.message);
			// 		}
			// 	});
			// }

			function DeleteItem(itemID, controller, action, paramName = 'itemID', deleteMethod = 'DeleteImage') {
				debugger;
				let data = {};
				data[paramName] = itemID;

				$.ajax({
					url: `/${controller}/${deleteMethod}`,
					type: 'POST',
					data: data,
					success: function (op) {
						if (op.success) {
							let sendingUrl = `/${controller}/${action}`;
							$.get(sendingUrl, null, function (receivingData) {
								$("#dvContent").html(receivingData);
								BindGrid();
								SuccessMessage(operationResult.message);
							});
						} else {
							// alert(op.message);
							ErrorMessage(operationResult.message);
						}
					},
					error: function (xhr, status, error) {
						console.error('Error:', error);
						alert('An error occurred while processing your request.');
					}
				});
			}






			//Add
			$(document).on("click", ".btn-add", function () {
				let action = $(this).attr("data-action");
				let controller = $(this).attr("data-controller");
				let sendingUrl = `/${controller}/${action}`;
				let sendingData = null;
				$.get(sendingUrl, sendingData, function (frmAdd) {
					$("#dvModalContent").html(frmAdd);
					$("#mainModal").modal("show");
				});
			});

			//saveAdd
			$(document).on("click", ".saveAdd", function () {
				debugger;
				let action = $(this).attr("data-action");
				let controller = $(this).attr("data-controller");
				let formid = "#" + $(this).attr("data-form-id");
				let sendingUrl = `/${controller}/${action}`;
				let sendingData = $(formid).serialize();
				$.post(sendingUrl, sendingData, function (op) {
					if (op.success.toString() == "true") {

						$("#mainModal").modal("hide");
						BindGrid();
						SuccessMessage(op.message);

					}
					else {
						ErrorMessage(op.message);
					}
				});
			});



			//Update
			$(document).on("click", ".btn-update", function () {

				let action = $(this).attr("data-action");
				let controller = $(this).attr("data-controller");
				let id = $(this).attr("data-id");
				let sendingUrl = `/${controller}/${action}`;
				let sendingData = `id=${id}`;
				$.get(sendingUrl, sendingData, function (frmUpdate) {
					console.log(frmUpdate);
					$("#dvModalContent").html(frmUpdate);// in information masalan newsCategory ro da modal jai gozary mikone
					$("#mainModal").modal("show");
				});
			});

			//saveUpdate
			$(document).on("click", ".saveUpdate", function () {
				let action = $(this).attr("data-action");
				let controller = $(this).attr("data-controller");
				let formid = "#" + $(this).attr("data-form-id");

				let sendingUrl = `/${controller}/${action}`;
				let sendingData = $(formid).serialize();
				$.post(sendingUrl, sendingData, function (op) {
					if (op.success.toString() == "true") {

						$("#mainModal").modal("hide");
						BindGrid();
						SuccessMessage(op.message);
					}
					else {
						ErrorMessage(op.message);
					}
				});
			});


		</script>

	</body>
</html>

<div class="modal" tabindex="-1" id="mainModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Modal title</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body" id="dvModalContent">
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Save changes</button>
			</div>
		</div>
	</div>
</div>

</body>
</html>